/**
 * 覆盖层 UI 模板（HTML 与 CSS）
 * 方向 C：悬浮球模式 —— 右下角悬浮球 + 按需弹出小面板
 */
const FONT_INLINE = require('./font-inline');

const OVERLAY_HTML = [
'<div id="estrix-overlay" class="estrix-overlay estrix-hidden">',
'  <div class="estrix-header">',
'    <span class="estrix-title">Estrix Code</span>',
'    <button id="estrix-btn-minimize" class="estrix-btn-icon" title="收起">×</button>',
'  </div>',
'  <div class="estrix-body">',
'    <div class="estrix-actions">',
'      <button id="estrix-btn-init" class="estrix-btn estrix-btn-primary">初始化项目</button>',
'    </div>',
'    <div class="estrix-section">',
'      <label class="estrix-label">当前命令</label>',
'      <pre id="estrix-cmd-preview" class="estrix-cmd-preview">暂无</pre>',
'    </div>',
'    <div class="estrix-section">',
'      <details id="estrix-history">',
'        <summary class="estrix-label">最近命令</summary>',
'        <div id="estrix-history-list" class="estrix-history-list"></div>',
'        <button id="estrix-btn-clear" class="estrix-btn-text">清空</button>',
'      </details>',
'    </div>',
'    <div class="estrix-actions">',
'      <button id="estrix-btn-open-settings" class="estrix-btn estrix-btn-secondary">打开设置</button>',
'    </div>',
'  </div>',
'</div>',
'<div id="estrix-status-badge" title="Estrix Code 运行中">',
'  <span id="estrix-status-dot"></span>',
'  <span class="estrix-fab-icon">E</span>',
'</div>',
].join('\n');

const OVERLAY_CSS = [
'@font-face {',
'  font-family: "HarmonyOS Sans SC";',
'  src: url(' + JSON.stringify(FONT_INLINE) + ') format("woff2");',
'  font-weight: 400;',
'  font-style: normal;',
'  font-display: swap;',
'}',
':root {',
'  --ck-bg: rgba(23, 24, 28, 0.97);',
'  --ck-surface: rgba(255, 255, 255, 0.045);',
'  --ck-surface-hover: rgba(255, 255, 255, 0.08);',
'  --ck-border: rgba(255, 255, 255, 0.08);',
'  --ck-primary: #5eb0ef;',
'  --ck-primary-strong: #4a9de0;',
'  --ck-text: #e8eaee;',
'  --ck-text-dim: #8b8f9a;',
'  --ck-green: #4ec98a;',
'  --ck-red: #e5646e;',
'  --ck-code-bg: rgba(0, 0, 0, 0.4);',
'  --ck-font: "HarmonyOS Sans SC", -apple-system, "Segoe UI", "PingFang SC", sans-serif;',
'  --ck-font-mono: "Cascadia Code", "JetBrains Mono", Consolas, monospace;',
'  --ck-ease: cubic-bezier(0.32, 0.72, 0, 1);',
'  --ck-radius: 12px;',
'}',
'.estrix-overlay {',
'  position: fixed; bottom: 84px; right: 24px; width: 300px; max-height: 64vh;',
'  background: var(--ck-bg);',
'  border: 1px solid var(--ck-border);',
'  border-radius: 16px;',
'  z-index: 2147483647;',
'  display: flex; flex-direction: column; overflow: hidden;',
'  box-shadow: 0 16px 48px rgba(0, 0, 0, 0.5);',
'  transition: opacity 0.2s var(--ck-ease), transform 0.2s var(--ck-ease);',
'  font-family: var(--ck-font);',
'  color: var(--ck-text); font-size: 13px; line-height: 1.55;',
'  backdrop-filter: blur(20px); -webkit-backdrop-filter: blur(20px);',
'}',
'.estrix-overlay.estrix-hidden { opacity: 0; pointer-events: none; transform: translateY(8px) scale(0.98); }',
'.estrix-header {',
'  display: flex; align-items: center; justify-content: space-between;',
'  padding: 14px 16px 12px; flex-shrink: 0;',
'  border-bottom: 1px solid var(--ck-border);',
'}',
'.estrix-title { font-size: 13.5px; font-weight: 500; color: var(--ck-text); letter-spacing: 0.2px; }',
'.estrix-btn-icon {',
'  display: grid; place-items: center;',
'  width: 26px; height: 26px; border: none; border-radius: 8px;',
'  background: transparent; color: var(--ck-text-dim); cursor: pointer; font-size: 15px;',
'  transition: background 0.16s var(--ck-ease), color 0.16s var(--ck-ease);',
'}',
'.estrix-btn-icon:hover { background: var(--ck-surface-hover); color: var(--ck-text); }',
'.estrix-body { padding: 14px 16px 16px; overflow-y: auto; flex: 1; display: flex; flex-direction: column; gap: 14px; }',
'.estrix-body::-webkit-scrollbar { width: 8px; }',
'.estrix-body::-webkit-scrollbar-thumb { background: rgba(128,128,128,0.28); border-radius: 4px; border: 2px solid transparent; background-clip: padding-box; }',
'.estrix-section { display: flex; flex-direction: column; gap: 8px; }',
'.estrix-label { font-size: 11px; font-weight: 500; color: var(--ck-text-dim); text-transform: uppercase; letter-spacing: 0.8px; cursor: pointer; }',
'.estrix-cmd-preview {',
'  background: var(--ck-code-bg); border: 1px solid var(--ck-border);',
'  border-radius: 10px; padding: 10px 12px; margin: 0;',
'  font-family: var(--ck-font-mono); font-size: 12px; color: var(--ck-green); line-height: 1.5;',
'  max-height: 140px; overflow: auto; white-space: pre-wrap; word-break: break-all;',
'}',
'.estrix-actions { display: flex; gap: 8px; }',
'.estrix-actions .estrix-btn { flex: 1; }',
'.estrix-btn {',
'  padding: 9px 14px; border: 1px solid transparent; border-radius: 10px;',
'  font-family: inherit; font-size: 12.5px; font-weight: 500; cursor: pointer;',
'  transition: background 0.16s var(--ck-ease), transform 0.16s var(--ck-ease), box-shadow 0.16s var(--ck-ease);',
'}',
'.estrix-btn:active { transform: scale(0.98); }',
'.estrix-btn-primary { background: var(--ck-primary); color: #fff; }',
'.estrix-btn-primary:hover { background: var(--ck-primary-strong); box-shadow: 0 6px 16px rgba(94,176,239,0.3); }',
'.estrix-btn-primary:disabled { opacity: 0.5; cursor: not-allowed; }',
'.estrix-btn-secondary { background: var(--ck-surface); color: var(--ck-text); border-color: var(--ck-border); }',
'.estrix-btn-secondary:hover { background: var(--ck-surface-hover); }',
'.estrix-btn-text { background: none; border: none; color: var(--ck-text-dim); padding: 4px 0; text-align: left; font-size: 11px; cursor: pointer; font-family: inherit; transition: color 0.16s var(--ck-ease); }',
'.estrix-btn-text:hover { color: var(--ck-red); }',
'.estrix-history-list { max-height: 160px; overflow-y: auto; display: flex; flex-direction: column; gap: 6px; margin-top: 6px; }',
'.estrix-history-item { background: var(--ck-surface); border-radius: 8px; padding: 8px 10px; font-size: 12px; cursor: pointer; transition: background 0.16s var(--ck-ease); }',
'.estrix-history-item:hover { background: var(--ck-surface-hover); }',
'.estrix-history-item .estrix-cmd-text { font-family: var(--ck-font-mono); color: var(--ck-green); font-size: 11.5px; display: block; overflow: hidden; text-overflow: ellipsis; white-space: nowrap; }',
'.estrix-history-item .estrix-cmd-status { font-size: 11px; margin-top: 2px; display: block; }',
'.estrix-history-item .estrix-cmd-status.success { color: var(--ck-green); }',
'.estrix-history-item .estrix-cmd-status.error { color: var(--ck-red); }',
'.estrix-history-item .estrix-cmd-time { font-size: 10px; color: var(--ck-text-dim); margin-top: 2px; display: block; }',
'#estrix-status-badge {',
'  position: fixed; bottom: 24px; right: 24px; z-index: 2147483647;',
'  width: 46px; height: 46px; border-radius: 50%;',
'  background: var(--ck-bg); border: 1px solid var(--ck-border);',
'  display: flex; align-items: center; justify-content: center;',
'  cursor: pointer;',
'  transition: background 0.18s var(--ck-ease), border-color 0.18s var(--ck-ease), transform 0.18s var(--ck-ease);',
'  box-shadow: 0 6px 20px rgba(0,0,0,0.4);',
'  backdrop-filter: blur(20px); -webkit-backdrop-filter: blur(20px);',
'}',
'#estrix-status-badge:hover { transform: scale(1.06); }',
'#estrix-status-badge.estrix-running { border-color: rgba(78,201,138,0.6); }',
'#estrix-status-dot {',
'  position: absolute; top: 5px; right: 5px;',
'  width: 9px; height: 9px; border-radius: 50%;',
'  background: var(--ck-text-dim); transition: background 0.2s var(--ck-ease);',
'}',
'#estrix-status-dot.estrix-running { background: var(--ck-green); animation: estrix-pulse 1.6s infinite; }',
'.estrix-fab-icon { font-size: 19px; font-weight: 600; color: var(--ck-text); line-height: 1; user-select: none; }',
'#estrix-status-badge.estrix-running .estrix-fab-icon { color: var(--ck-green); }',
'.estrix-toast {',
'  position: fixed; top: 18px; left: 50%; transform: translateX(-50%) translateY(-8px);',
'  z-index: 2147483648; min-width: 200px; max-width: 380px; text-align: center;',
'  background: var(--ck-bg); border: 1px solid var(--ck-border); border-radius: 12px;',
'  padding: 10px 16px; font-size: 13px; color: var(--ck-text); font-family: var(--ck-font);',
'  box-shadow: 0 10px 30px rgba(0,0,0,0.4);',
'  opacity: 0; pointer-events: none; transition: opacity 0.2s var(--ck-ease), transform 0.2s var(--ck-ease);',
'}',
'.estrix-toast.show { opacity: 1; transform: translateX(-50%) translateY(0); }',
'.estrix-task-status { display: inline-flex; align-items: center; gap: 5px; color: var(--ck-green); font-size: 11px; font-weight: 500; }',
'/* 强制网页也用 HarmonyOS 字体 */',
'html body, html body *:not(code):not(pre):not([class*="code"]):not([class*="mono"]), html body input, html body textarea, html body button, html body select, html body [contenteditable] { font-family: "HarmonyOS Sans SC", -apple-system, "Segoe UI", "PingFang SC", sans-serif !important; }',
'@keyframes estrix-pulse { 0%,100% { opacity: 1; } 50% { opacity: 0.4; } }',
].join('\n');

module.exports = { OVERLAY_HTML, OVERLAY_CSS };
