/**
 * 覆盖层 UI 模板（HTML 与 CSS）
 * 方向 C：悬浮球模式 —— 右下角悬浮球 + 按需弹出小面板
 */
const OVERLAY_HTML = [
'<div id="estrix-overlay" class="estrix-overlay estrix-hidden">',
'  <div class="estrix-header">',
'    <span class="estrix-title">Estrix Code</span>',
'    <button id="estrix-btn-minimize" class="estrix-btn-icon" title="收起">×</button>',
'  </div>',
'  <div class="estrix-body">',
'    <div class="estrix-section">',
'      <label class="estrix-label">当前命令</label>',
'      <pre id="estrix-cmd-preview" class="estrix-cmd-preview">暂无</pre>',
'    </div>',
'    <div class="estrix-section">',
'      <details id="estrix-history">',
'        <summary class="estrix-label">最近命令</summary>',
'        <div id="estrix-history-list" class="estrix-history-list"></div>',
'        <button id="estrix-btn-clear" class="estrix-btn-text">清空</button>',
'      </details>',
'    </div>',
'    <div class="estrix-actions">',
'      <button id="estrix-btn-open-settings" class="estrix-btn estrix-btn-primary">打开设置</button>',
'    </div>',
'  </div>',
'</div>',
'<div id="estrix-status-badge" title="Estrix Code 运行中">',
'  <span id="estrix-status-dot"></span>',
'  <span class="estrix-fab-icon">E</span>',
'</div>',
].join('\n');

const OVERLAY_CSS = [
':root {',
'  /* Soft 风：中性蓝灰，去 AI 紫 */',
'  --ck-bg: rgba(23, 24, 28, 0.97);',
'  --ck-surface: rgba(255, 255, 255, 0.045);',
'  --ck-surface-hover: rgba(255, 255, 255, 0.08);',
'  --ck-border: rgba(255, 255, 255, 0.08);',
'  --ck-primary: #5eb0ef;',
'  --ck-primary-strong: #4a9de0;',
'  --ck-text: #e8eaee;',
'  --ck-text-dim: #8b8f9a;',
'  --ck-green: #4ec98a;',
'  --ck-red: #e5646e;',
'  --ck-code-bg: rgba(0, 0, 0, 0.4);',
'  --ck-font-mono: "Cascadia Code", "JetBrains Mono", "Fira Code", Consolas, "PingFang SC", "Microsoft YaHei", monospace;',
'}',
'.estrix-overlay {',
'  position: fixed; bottom: 84px; right: 24px; width: 300px; max-height: 60vh;',
'  background: rgba(17, 19, 34, 0.98);',
'  border: 1px solid var(--ck-border);',
'  border-radius: 16px;',
'  z-index: 2147483647;',
'  will-change: transform;',
'  display: flex; flex-direction: column;',
'  box-shadow: 0 12px 40px rgba(0, 0, 0, 0.45), 0 0 0 1px rgba(94,176,239,0.06);',
'  transition: opacity 0.22s cubic-bezier(0.32,0.72,0,1), transform 0.22s cubic-bezier(0.32,0.72,0,1);',
'  font-family: "HarmonyOS Sans SC", -apple-system, BlinkMacSystemFont, "Segoe UI", "PingFang SC", sans-serif;',
'  color: var(--ck-text); font-size: 13px; line-height: 1.55;',
'  overflow: hidden;',
'}',
'.estrix-overlay.estrix-hidden { opacity: 0; pointer-events: none; transform: translateY(8px); }',
'.estrix-header {',
'  display: flex; align-items: center; justify-content: space-between;',
'  padding: 12px 16px 10px; flex-shrink: 0;',
'  border-bottom: 1px solid var(--ck-border);',
'  background: rgba(255, 255, 255, 0.02);',
'}',
'.estrix-title { font-size: 14px; font-weight: 700; color: var(--ck-text); letter-spacing: 0.4px; }',
'.estrix-btn-icon {',
'  background: var(--ck-surface); border: 1px solid var(--ck-border); color: var(--ck-text-dim);',
'  cursor: pointer; font-size: 16px; width: 28px; height: 28px; border-radius: 8px;',
'  display: flex; align-items: center; justify-content: center; transition: all 0.18s cubic-bezier(0.32,0.72,0,1);',
'  line-height: 1;',
'}',
'.estrix-btn-icon:hover { background: var(--ck-surface-hover); color: #fff; }',
'.estrix-body { padding: 12px 14px; overflow-y: auto; flex: 1; display: flex; flex-direction: column; gap: 12px; }',
'.estrix-section { display: flex; flex-direction: column; gap: 8px; }',
'.estrix-label { font-size: 11px; font-weight: 700; color: var(--ck-text-dim); text-transform: uppercase; letter-spacing: 1px; cursor: pointer; }',
'.estrix-cmd-preview {',
'  background: var(--ck-code-bg); border: 1px solid var(--ck-border);',
'  border-radius: 12px; padding: 10px 12px;',
'  font-family: var(--ck-font-mono);',
'  font-size: 12px; color: var(--ck-green); line-height: 1.5;',
'  max-height: 140px; overflow: auto; white-space: pre-wrap; word-break: break-all; margin: 0;',
'}',
'.estrix-actions { display: flex; gap: 8px; width: 100%; }',
'.estrix-actions .estrix-btn { flex: 1 1 auto; }',
'.estrix-btn {',
'  flex: 1; padding: 9px 14px; border: 1px solid transparent; border-radius: 10px;',
'  font-size: 12.5px; font-weight: 600; cursor: pointer;',
'  transition: all 0.18s cubic-bezier(0.32,0.72,0,1); letter-spacing: 0.3px;',
'}',
'.estrix-btn:active { transform: scale(0.98); }',
'.estrix-btn-primary {',
'  background: linear-gradient(135deg, var(--ck-primary), var(--ck-primary-strong)); color: #fff;',
'  box-shadow: 0 6px 18px rgba(74,157,224,0.25);',
'}',
'.estrix-btn-primary:hover { box-shadow: 0 8px 22px rgba(74,157,224,0.4); transform: translateY(-1px); }',
'.estrix-btn-primary:disabled { opacity: 0.5; cursor: not-allowed; transform: none; }',
'.estrix-btn-secondary {',
'  background: var(--ck-surface); color: var(--ck-text);',
'  border-color: var(--ck-border);',
'}',
'.estrix-btn-secondary:hover { background: var(--ck-surface-hover); color: #fff; border-color: rgba(94,176,239,0.4); }',
'.estrix-btn-text {',
'  background: none; border: none; color: var(--ck-text-dim); padding: 4px 0;',
'  text-align: left; font-size: 11px; cursor: pointer; transition: color 0.18s cubic-bezier(0.32,0.72,0,1);',
'}',
'.estrix-btn-text:hover { color: var(--ck-red); }',
'.estrix-result-status { font-size: 12px; font-weight: 600; padding: 2px 0; }',
'.estrix-result-status.success { color: var(--ck-green); }',
'.estrix-result-status.error { color: var(--ck-red); }',
'.estrix-result-output {',
'  background: var(--ck-code-bg); border: 1px solid var(--ck-border);',
'  border-radius: 12px; padding: 10px 12px;',
'  font-family: var(--ck-font-mono);',
'  font-size: 11.5px; color: var(--ck-text); line-height: 1.5;',
'  max-height: 200px; overflow: auto; white-space: pre-wrap; word-break: break-all; margin: 0;',
'}',
'.estrix-history-list { max-height: 140px; overflow-y: auto; display: flex; flex-direction: column; gap: 8px; }',
'.estrix-history-item {',
'  background: var(--ck-surface); border-radius: 10px; padding: 8px 10px;',
'  font-size: 12px; cursor: pointer; transition: background 0.18s cubic-bezier(0.32,0.72,0,1);',
'}',
'.estrix-history-item:hover { background: rgba(94,176,239,0.18); }',
'.estrix-history-item .estrix-cmd-text {',
'  font-family: var(--ck-font-mono); color: var(--ck-green); font-size: 12px;',
'  display: block; overflow: hidden; text-overflow: ellipsis; white-space: nowrap;',
'}',
'.estrix-history-item .estrix-cmd-status { font-size: 11px; margin-top: 2px; display: block; }',
'.estrix-history-item .estrix-cmd-status.success { color: var(--ck-green); }',
'.estrix-history-item .estrix-cmd-status.error { color: var(--ck-red); }',
'.estrix-history-item .estrix-cmd-time { font-size: 10px; color: var(--ck-text-dim); margin-top: 2px; display: block; }',
'#estrix-mcp-manager { width: 780px; max-width: 90vw; }',
'#estrix-mcp-manager .estrix-mcp-body { flex-direction: row; gap: 12px; align-items: stretch; overflow: hidden; }',
'.estrix-mcp-left { width: 220px; flex-shrink: 0; display: flex; flex-direction: column; }',
'.estrix-mcp-left .estrix-session-list { flex: 1; max-height: none; overflow-y: auto; }',
'.estrix-mcp-right { flex: 1; display: flex; flex-direction: column; gap: 12px; }',
'.estrix-mcp-json { flex: 1; min-height: 55vh; resize: vertical; }',
'.estrix-mcp-right .estrix-btn { flex: 0 0 auto; align-self: flex-start; }',
'.estrix-window-manager {',
'  position: fixed; top: 50%; left: 50%; transform: translate(-50%, -50%);',
'  z-index: 2147483647; width: 520px; height: 80vh; max-height: 85vh;',
'  background: rgba(17, 19, 34, 0.98);',
'  border: 1px solid var(--ck-border); border-radius: 16px;',
'  display: flex; flex-direction: column; overflow: hidden;',
'  box-shadow: 0 16px 50px rgba(0, 0, 0, 0.55), 0 0 0 1px rgba(94, 176, 239, 0.08);',
'  transition: opacity 0.22s cubic-bezier(0.32,0.72,0,1), transform 0.22s cubic-bezier(0.32,0.72,0,1);',
'}',
'.estrix-window-manager.estrix-hidden { opacity: 0; pointer-events: none; transform: translate(-50%, -50%) scale(0.95); }',
'.estrix-wm-header {',
'  display: flex; align-items: center; justify-content: space-between;',
'  padding: 12px 16px 10px; flex-shrink: 0;',
'  border-bottom: 1px solid var(--ck-border);',
'  background: rgba(255, 255, 255, 0.02);',
'}',
'.estrix-wm-body { padding: 12px 14px; overflow: hidden; flex: 1; display: flex; flex-direction: column; gap: 12px; }',
'.estrix-window-item {',
'  display: flex; align-items: center; justify-content: space-between;',
'  background: var(--ck-surface); border: 1px solid var(--ck-border);',
'  border-radius: 10px; padding: 10px 12px; cursor: pointer;',
'  transition: background 0.18s cubic-bezier(0.32,0.72,0,1); font-size: 12px;',
'  gap: 8px;',
'}',
'.estrix-window-item:hover { background: rgba(94,176,239,0.18); }',
'.estrix-window-left { display: flex; align-items: center; gap: 8px; flex: 1; min-width: 0; }',
'.estrix-window-item .estrix-window-name { color: var(--ck-text); font-weight: 600; flex-shrink: 0; }',
'.estrix-window-item .estrix-window-sep { color: var(--ck-text-dim); flex-shrink: 0; }',
'.estrix-window-item .estrix-window-status { color: var(--ck-text-dim); font-size: 11px; overflow: hidden; text-overflow: ellipsis; white-space: nowrap; }',
'.estrix-window-del {',
'  color: var(--ck-red); cursor: pointer; font-size: 11px; padding: 2px 6px;',
'  border-radius: 6px; flex-shrink: 0; transition: all 0.18s cubic-bezier(0.32,0.72,0,1);',
'}',
'.estrix-window-del:hover { background: rgba(255, 107, 122, 0.18); color: #fff; }',
'.estrix-window-item.active { border-color: rgba(94, 176, 239, 0.5); background: rgba(94, 176, 239, 0.12); }',
'#estrix-window-list { max-height: none; flex: 1; min-height: 200px; overflow-y: auto; }',
'#estrix-window-list .estrix-window-item { flex-shrink: 0; }',
'#estrix-status-badge {',
'  position: fixed; bottom: 24px; right: 24px; z-index: 2147483647;',
'  width: 48px; height: 48px; border-radius: 50%;',
'  background: rgba(94,176,239,0.22); border: 1px solid rgba(94,176,239,0.4);',
'  will-change: transform;',
'  display: flex; align-items: center; justify-content: center; gap: 0;',
'  cursor: pointer;',
'  transition: background 0.18s cubic-bezier(0.32,0.72,0,1), border-color 0.18s cubic-bezier(0.32,0.72,0,1), transform 0.18s cubic-bezier(0.32,0.72,0,1);',
'}',
'#estrix-status-badge:hover { background: rgba(94,176,239,0.35); border-color: rgba(94,176,239,0.65); transform: scale(1.05); }',
'#estrix-status-badge.estrix-running { background: rgba(34, 197, 94, 0.28); border-color: rgba(34, 197, 94, 0.7); animation: estrix-running-glow 1.5s ease-in-out infinite; }',
'#estrix-status-badge.estrix-running .estrix-fab-icon { color: #7cffb2; }',
'#estrix-status-dot.estrix-running { background: #22c55e; }',
'@keyframes estrix-running-glow { 0%, 100% { box-shadow: 0 0 0 0 rgba(34,197,94,0.5); } 50% { box-shadow: 0 0 0 6px rgba(34,197,94,0); } }',
'#estrix-status-dot {',
'  position: absolute; top: 6px; right: 6px;',
'  width: 9px; height: 9px; border-radius: 50%;',
'  background: var(--ck-green); animation: estrix-pulse 2s infinite;',
'}',
'.estrix-fab-icon {',
'  font-size: 22px; font-weight: 800; color: var(--ck-primary); line-height: 1;',
'  user-select: none;',
'}',
'.estrix-toast {',
'  position: fixed; top: 18px; left: 50%; transform: translateX(-50%) translateY(-8px);',
'  z-index: 2147483648; min-width: 200px; max-width: 380px; text-align: center;',
'  background: rgba(22, 24, 44, 0.92); backdrop-filter: blur(18px);',
'  -webkit-backdrop-filter: blur(18px);',
'  border: 1px solid rgba(94, 176, 239, 0.28); border-radius: 12px;',
'  padding: 10px 16px; font-size: 13px; color: var(--ck-text);',
'  box-shadow: 0 10px 30px rgba(0, 0, 0, 0.35);',
'  opacity: 0; pointer-events: none; transition: opacity 0.22s cubic-bezier(0.32,0.72,0,1), transform 0.22s cubic-bezier(0.32,0.72,0,1);',
'}',
'.estrix-toast.show { opacity: 1; transform: translateX(-50%) translateY(0); }',
'.estrix-task-status {',
'  display: inline-flex; align-items: center; gap: 4px;',
'  color: var(--ck-primary); font-size: 11px; font-weight: 600;',
'}',
'.estrix-spinner {',
'  width: 11px; height: 11px; border-radius: 50%;',
'  border: 2px solid rgba(94,176,239,0.25); border-top-color: var(--ck-primary);',
'  animation: estrix-spin 0.8s linear infinite;',
'}',
'@keyframes estrix-spin { to { transform: rotate(360deg); } }',
'@keyframes estrix-pulse { 0%, 100% { opacity: 1; } 50% { opacity: 0.35; } }',
'@keyframes estrix-attention {',
'  0%, 100% { transform: scale(1); }',
'  10%, 30%, 50%, 70%, 90% { transform: scale(1.08); }',
'  20%, 40%, 60%, 80% { transform: scale(0.98); }',
'}',
'.estrix-btn-attention {',
'  animation: estrix-attention 1s ease-in-out 3;',
'  background: rgba(94,176,239,0.35) !important;',
'  color: #fff !important;',
'  border-color: rgba(94, 176, 239, 0.6) !important;',
'}',
'.estrix-hidden { display: none !important; }',
'.estrix-home-mode .estrix-header .estrix-btn-icon,',
'.estrix-home-mode .estrix-body .estrix-section,',
'.estrix-home-mode .estrix-body .estrix-actions:not(:has(#estrix-btn-init)),',
'.estrix-home-mode .estrix-divider {',
'  display: none !important;',
'}',
'.estrix-overlay ::-webkit-scrollbar { width: 6px; }',
'.estrix-overlay ::-webkit-scrollbar-track { background: transparent; }',
'.estrix-overlay ::-webkit-scrollbar-thumb { background: var(--ck-surface-hover); border-radius: 3px; }',
'.estrix-overlay ::-webkit-scrollbar-thumb:hover { background: rgba(255,255,255,0.25); }',
'.estrix-project-dir-section {',
'  background: var(--ck-surface); border-radius: 10px;',
'  padding: 8px 10px; border: 1px solid var(--ck-border);',
'}',
'.estrix-project-dir-row { display: flex; justify-content: space-between; align-items: center; }',
'.estrix-btn-change-dir {',
'  background: rgba(94,176,239,0.2); border: none;',
'  color: var(--ck-primary); padding: 2px 8px; border-radius: 6px;',
'  cursor: pointer; font-size: 11px; font-weight: 600;',
'}',
'.estrix-btn-change-dir:hover { background: rgba(94,176,239,0.4); }',
'.estrix-project-dir-display { margin-top: 4px; font-size: 12px; font-family: var(--ck-font-mono); color: var(--ck-text-dim); word-break: break-all; }',
'.estrix-dir-path { color: var(--ck-green); }',
'.estrix-divider { border-top: 1px solid var(--ck-border); margin: 2px 0; }',
'.estrix-session-section {',
'  background: var(--ck-surface); border-radius: 10px;',
'  padding: 8px 10px; border: 1px solid var(--ck-border);',
'}',
'.estrix-session-header { display: flex; justify-content: space-between; align-items: center; }',
'.estrix-btn-refresh-sessions {',
'  background: rgba(94,176,239,0.2); border: none;',
'  color: var(--ck-primary); padding: 2px 8px; border-radius: 6px;',
'  cursor: pointer; font-size: 11px; font-weight: 600;',
'}',
'.estrix-btn-refresh-sessions:hover { background: rgba(94,176,239,0.4); }',
'.estrix-session-list { max-height: 100px; overflow-y: auto; margin-top: 4px; display: flex; flex-direction: column; gap: 4px; }',
'.estrix-session-item { background: var(--ck-surface); border-radius: 8px; padding: 6px 10px; font-size: 12px; font-family: var(--ck-font-mono); color: var(--ck-text); cursor: pointer; transition: background 0.18s cubic-bezier(0.32,0.72,0,1); }',
'.estrix-session-item:hover { background: rgba(94,176,239,0.2); }',
'.estrix-session-item .session-id { color: var(--ck-primary); font-size: 11px; }',
'.estrix-session-item .session-action { color: var(--ck-green); font-size: 11px; font-weight: 600; }',
'.estrix-session-empty { color: var(--ck-text-dim); font-size: 12px; font-style: italic; padding: 8px 0; text-align: center; }',
'.estrix-first-time-dialog {',
'  position: fixed; top: 0; left: 0; right: 0; z-index: 2147483647;',
'  display: flex; align-items: flex-start; justify-content: center;',
'  padding-top: 24px;',
'  pointer-events: none;',
'}',
'.estrix-first-time-dialog.estrix-hidden { display: none !important; }',
'.estrix-first-time-box {',
'  position: relative; max-width: 420px; width: 90%;',
'  background: rgba(17, 19, 34, 0.98);',
'  border: 1px solid rgba(94,176,239,0.35);',
'  border-radius: 18px;',
'  padding: 28px 24px 22px;',
'  box-shadow: 0 20px 60px rgba(0, 0, 0, 0.6), 0 0 0 1px rgba(94, 176, 239, 0.08);',
'  color: var(--ck-text); font-size: 14px; line-height: 1.6;',
'  text-align: center;',
'  pointer-events: auto;',
'}',
'.estrix-first-time-close { position: absolute; top: 10px; right: 10px; }',
'.estrix-first-time-text { margin-bottom: 18px; color: var(--ck-text); }',
'.estrix-first-time-box .estrix-actions { justify-content: center; }',
'.estrix-first-time-box .estrix-btn { flex: 0 0 auto; min-width: 150px; }',
].join('\n');

module.exports = { OVERLAY_HTML, OVERLAY_CSS };
